### ISSUE TITLE
Where is config.js

### ISSUE THREAD

**Issue by noraa-junker** [magnusmanske/wikistream#1]
`public_html/index.html` mentions a config.js. Where is it and what does it include?

**Comment by magnusmanske** [comment]
`config.js` is created when running `scripts/update.php`. This is to generate a single dataset, mostly for the main page. I'll add a note to the README.

**Comment by noraa-junker** [comment]
Thank you!

**Comment by noraa-junker** [comment]
Another question: When I try to run your linked script it reports that `public_html/php/ToolforgeCommon.php` is missing. Where do I get this file from? Or do I have to test edits in Toolforge?

**Comment by magnusmanske** [comment]
I have my own shared "libraries".

PHP ones are in https://bitbucket.org/magnusmanske/magnustools/src/master/public_html/php/

JS ones are in https://bitbucket.org/magnusmanske/magnustools/src/master/public_html/resources/

**Comment by noraa-junker** [comment]
> I have my own shared "libraries".
> 
> PHP ones are in https://bitbucket.org/magnusmanske/magnustools/src/master/public_html/php/
> 
> JS ones are in https://bitbucket.org/magnusmanske/magnustools/src/master/public_html/resources/

Oh I see. Would it be a possibility to include these as Git submodules? That would simplify setting up the repo a lot. I could do this if you would give the ok

**Comment by magnusmanske** [comment]
Sure, go ahead!

**Comment by noraa-junker** [comment]
Ok the gitmodues thing won't work, because you cannot add a submodule to the root. How do you use these two repositories together on your machine?
